1.	Assume you run a small security company that provides physical security services in the area and you recently won a new contract in the area to provide 24x7 security to a small building under construction.  For simplicity we will design the solution for only 24 hours, but if you want to go above and beyond, feel free to write code that handles the 24x7 scenario as well.

2.	You have 6 security guards available at the moment who you can assign to this building but your goal is to make more money out of this contract and spend less in wages (hence greedy!)

3.	The cost/wage structure is as follows:

o	People working less than or equal to 8 hours will be paid $15/hr

o	Anyone working overtime (>8 hours) will be paid an additional $5, i.e. $20/hr

4.	Create a greedy algorithm (come up with any algorithm of your own) that finds you the most cost effective solution e.g. Should we appoint 2 security guards for 12 hours each? Or 3 of them for 8 hours each? Or 4 for 6 hours each? Or all 6 for 4 hours each? Or any other combination?

Write the greedy algorithm, run it, and record the solution that your algorithm produces.  Please answer the following questions regarding your solution:

o	Explain your algorithm in detail.  How is it greedy?

o	What is the complexity of your solution?

o	Did the greedy algorithm provide the best solution or could there be an alternative/better solution to your problem?  Why or why not?

o	If the scenario had different values for the inputs would your algorithm still be successful?  Eg. more than 24 hours, higher overtime, shorter shifts, or values that don't factor so nicely.  Why or why not?  What things would change the optimal output?

o	If you were not constrained to a greedy algorithm, what approaches would you take to solve the problem?

In [1]:
import numpy as np
import pandas as pd

In [2]:
#ample code
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 27 18:01:32 2019

@author: dev2
"""

# You pass an array in, and it gets converted to a set.
states_needed = set(["mt", "wa", "or", "id", "nv", "ut", "ca", "az"])

stations = {}
stations["kone"] = set(["id", "nv", "ut"])
stations["ktwo"] = set(["wa", "id", "mt"])
stations["kthree"] = set(["or", "nv", "ca"])
stations["kfour"] = set(["nv", "ut"])
stations["kfive"] = set(["ca", "az"])

final_stations = set()

while states_needed:
  best_station = None
  states_covered = set()
  for station, states in stations.items():
   
    covered = states_needed & states

    if len(covered) > len(states_covered):
      best_station = station
      states_covered = covered

  states_needed -= states_covered
  final_stations.add(best_station)

print(final_stations)

{'ktwo', 'kone', 'kfive', 'kthree'}

# Assume you run a small security company that provides physical security services in the area and you recently won a new contract in the area to provide 24x7 security to a small building under construction. For simplicity we will design the solution for only 24 hours, but if you want to go above and beyond, feel free to write code that handles the 24x7 scenario as well.

# You have 6 security guards available at the moment who you can assign to this building but your goal is to make more money out of this contract and spend less in wages (hence greedy!)

# The cost/wage structure is as follows:

# o People working less than or equal to 8 hours will be paid $15/hr

# o Anyone working overtime (>8 hours) will be paid an additional  5,𝑖.𝑒. 20/hr

# Create a greedy algorithm (come up with any algorithm of your own) that finds you the most cost effective solution e.g. Should we appoint 2 security guards for 12 hours each? Or 3 of them for 8 hours each? Or 4 for 6 hours each? Or all 6 for 4 hours each? Or any other combination?

# I will create a greedy algorithm to that will select the most cost effective (and max hours) number of hours per day each employee will work for a week

create variables for the greedy algorithm schedule  function

In [3]:


# create varable to calcuate cost
# set variable for regular pay and overtime pay
work_overtime = 20
work_regular = 15

# create employee list
employees = ['employee_1', 'employee_2', 'employee_3', 'employee_4', 'employee_5', 'employee_6']

In [4]:
# min to max work hours per employee from 1 to 12
work_hours = np.linspace(1,12,12)

In [5]:
work_hours

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [6]:

# list 7 days of the week

days = ['mon','tue','wed','thur','fri','sat','sun']

Create function with input that can change the cut off for over time. The default is 8

In [7]:



# create a greedy algorithim with while loop that count the number of day 
# set the default over time cut off = 8 ()
def employee_schedule(cut_off=8):
# create  dictonary to save the employee weekly schedule 
    schedule ={}

    # create cost function if hour are >8 then cost per hour = 20 else it is 15
    cost = (lambda x: x*work_regular if w <=cut_off else (cut_off*work_regular) + (x-cut_off)* work_overtime) 


    day_hour = 0 # keep track of hour in a day. max 24 hours
    day_counter = 0 # to index the number of day of the week list 

    # create a schedule for 7 days of the week mon-sun 
    while day_counter <= 6:
          time = 0
          for e in employees:# loop over each emmployee 

            if day_hour >= 24: # if hour exceeds 24 hr change the day
                day_hour = 0
                day_counter +=1

                if day_counter >= 7: # break the loop if the day counter exceeds 6
                    break

                else:

                    #max_hour = None s
                    max_cost = None
                    work_hour = None
                    #max_hour = []
                    max_cost = [] # create a list to append all the hourly cost employee
                    work_hour = [] # # create a list to append all the  hour per employee
                    counter = 0

                    d = days[day_counter] # index the day list
                    for w in work_hours: #loop over the number of hours of work available per employee


                            #max_hour = w 

                            max_cost.append((cost(w))/w)
                            work_hour.append(w)
                            #print(max_cost)
                            if len(max_cost)<2:
                                max_sch = [w]
                                schedule[e,d]= max_sch
                                hours = []
                                for k, v in schedule: # to calculate total hour scheduled for a day
                                    if v==d:
                                        hours.append(schedule[k,v][0])
                                day_hour = sum(hours)

                                #day_hour += schedule[e,d][0]   

                            else:

                                counter =counter+ 1
                                hours = []
                                for k, v in schedule:# to calculate total hour scheduled for a day
                                    if v==d:
                                        hours.append(schedule[k,v][0])
                                day_hour = sum(hours) 

                                if max_cost[counter] > max_cost[counter-1] and day_hour <= 24 : # greedy selecion for max hour and max time

                                    max_sch = [work_hour[counter-1]]
                                    schedule[e,d] = max_sch
                                    counter +=1
                                    hours = []
                                    for k, v in schedule: # to calculate total hour scheduled for a day
                                        if v==d:
                                            hours.append(schedule[k,v][0])
                                    day_hour = sum(hours)
                                #day_hour += schedule[e,d][0]


                                    break
                                elif day_hour <= 24:
                                    #print(day_hour)
                                    max_sch = [w]
                                    schedule[e,d]= max_sch
                                    hours = []
                                    for k, v in schedule:# to calculate total hour scheduled for a day
                                        if v==d:
                                            hours.append(schedule[k,v][0])
                                    day_hour = sum(hours)
                                    if day_hour >=24:
                                        break


            else:
                #print (e)

                #max_hour = None
                max_cost = None
                work_hour = None
                #max_hour = []
                max_cost = [] # create a list to append all the hourly cost per employee
                work_hour = [] # # create a list to append all the  hour per per employee
                counter = 0
                #print (day_counter)


                d = days[day_counter] # index the days list
                for w in work_hours: #loop over the number of hours of work available per employee

                        #print (d)
                        #cost = (lambda x: x*15 if w <=8 else x* 20)   # create cost function if                 
                        #max_hour = w 

                        max_cost.append((cost(w))/w)
                        work_hour.append(w)
                        #print (max_cost)


                        if len(max_cost)<2:
                            max_sch = [w]
                            schedule[e,d]= max_sch
                            hours = []
                            for k, v in schedule: # to calculate total hour scheduled for a day
                                if v==d:
                                    hours.append(schedule[k,v][0])
                            day_hour = sum(hours)
                            #print(day_hour)

                            #day_hour += schedule[e,d][0] 


                        else:

                            counter =counter+ 1
                            hours = []
                            for k, v in schedule:# to calculate total hour scheduled for a day
                                if v==d:
                                    hours.append(schedule[k,v][0])
                            day_hour = sum(hours) 
                            #print(day_hour)


                            if max_cost[counter] > max_cost[counter-1] and day_hour <= 24 : # g # greedy selecion for max hour and max time


                                max_sch = [work_hour[counter-1]]
                                schedule[e,d] = max_sch
                                counter +=1
                                hours = []
                                for k, v in schedule:# to calculate total hour scheduled for a day
                                    if v==d:
                                        hours.append(schedule[k,v][0])
                                day_hour = sum(hours)
                                #print(day_hour)

                                #day_hour += schedule[e,d][0]

                                #print (max_sch)

                                break
                            elif day_hour <= 24:
                                #print(day_hour)
                                max_sch = [w]
                                schedule[e,d]= max_sch
                                hours = []
                                for k, v in schedule:# to calculate total hour scheduled for a day
                                    if v==d:
                                        hours.append(schedule[k,v][0])
                                day_hour = sum(hours)
                                if day_hour >=24:
                                    break



    return schedule

In [8]:
schedule = employee_schedule()

schedule

{('employee_1', 'mon'): [8.0],
 ('employee_2', 'mon'): [8.0],
 ('employee_3', 'mon'): [8.0],
 ('employee_4', 'tue'): [8.0],
 ('employee_5', 'tue'): [8.0],
 ('employee_6', 'tue'): [8.0],
 ('employee_1', 'wed'): [8.0],
 ('employee_2', 'wed'): [8.0],
 ('employee_3', 'wed'): [8.0],
 ('employee_4', 'thur'): [8.0],
 ('employee_5', 'thur'): [8.0],
 ('employee_6', 'thur'): [8.0],
 ('employee_1', 'fri'): [8.0],
 ('employee_2', 'fri'): [8.0],
 ('employee_3', 'fri'): [8.0],
 ('employee_4', 'sat'): [8.0],
 ('employee_5', 'sat'): [8.0],
 ('employee_6', 'sat'): [8.0],
 ('employee_1', 'sun'): [8.0],
 ('employee_2', 'sun'): [8.0],
 ('employee_3', 'sun'): [8.0]}

In [9]:
# set up varibles for data frame
worker = []
day = []
hours = []

for k, v in schedule:
    worker.append(k)
    day.append(v)
    hours.append(schedule[k,v][0])

In [10]:
# create data frame to show the employees , day and number of hours each employee work
table = pd.DataFrame({"Worker": worker,'Day': day, 'Hour': hours})
table

        Worker   Day  Hour
0   employee_1   mon   8.0
1   employee_2   mon   8.0
2   employee_3   mon   8.0
3   employee_4   tue   8.0
4   employee_5   tue   8.0
5   employee_6   tue   8.0
6   employee_1   wed   8.0
7   employee_2   wed   8.0
8   employee_3   wed   8.0
9   employee_4  thur   8.0
10  employee_5  thur   8.0
11  employee_6  thur   8.0
12  employee_1   fri   8.0
13  employee_2   fri   8.0
14  employee_3   fri   8.0
15  employee_4   sat   8.0
16  employee_5   sat   8.0
17  employee_6   sat   8.0
18  employee_1   sun   8.0
19  employee_2   sun   8.0
20  employee_3   sun   8.0

In [11]:
# pivot table to show the the days as index and employees and colomn names
table = pd.pivot_table(table, columns='Worker', index='Day', values = 'Hour', fill_value=0)

In [12]:
table

Worker  employee_1  employee_2  employee_3  employee_4  employee_5  employee_6
Day
fri              8           8           8           0           0           0
mon              8           8           8           0           0           0
sat              0           0           0           8           8           8
sun              8           8           8           0           0           0
thur             0           0           0           8           8           8
tue              0           0           0           8           8           8
wed              8           8           8           0           0           0

In [13]:
# add total hour row per employee per week
table["Total_hours"]= table.employee_1 +table.employee_2+ table.employee_3 +table.employee_4 +table.employee_5 +table.employee_6

In [14]:
table.loc['Total_Hours'] = table.sum()


table

Worker,employee_1,employee_2,employee_3,employee_4,employee_5,employee_6,Total_hours
Day,,,,,,,
fri,8,8,8,0,0,0,24
mon,8,8,8,0,0,0,24
sat,0,0,0,8,8,8,24
sun,8,8,8,0,0,0,24
thur,0,0,0,8,8,8,24
tue,0,0,0,8,8,8,24
wed,8,8,8,0,0,0,24
Total_Hours,32,32,32,24,24,24,168

# Write the greedy algorithm, run it, and record the solution that your algorithm produces. Please answer the following questions regarding your solution:

# o Explain your algorithm in detail. How is it greedy?

# o What is the complexity of your solution?

# o Did the greedy algorithm provide the best solution or could there be an alternative/better solution to your problem? Why or why not?

# o If the scenario had different values for the inputs would your algorithm still be successful? Eg. more than 24 hours, higher overtime, shorter shifts, or values that don't factor so nicely. Why or why not? What things would change the optimal output?

# o If you were not constrained to a greedy algorithm, what approaches would you take to solve the problem?


My algorithm tries to minimize the cost of the number of hours each worker works per shift per day and also tries to select the maximum number of hours each employee can work per shift without overtime. It starts with the first employee--once that employee reaches 8 hours for the day, then it changes the shift to the next employee. The first slot starts on Monday at 0:00 hrs and day changes when 24 hours is filled by the employee time slots. The algorithm is greedy because it fills up the first guard until he or she hits the overtime cut-off hour because it increases the average cost per hour. The above table shows that each employee is given a maximum shift of 8 hours and because there are 7 days and 6 employees, the first three employees get the additional Sunday shift. 

I have tested my algorithm to manage different cut off overtime hours and as long as the duration is a week and no employee has to work two different shifts in a day, the algorithm works. However, it cannot be extended for a month or year. It would require an additional high level validation above the day check and employee rotation tracking in the function call.

For the given problem, the greedy algorithm provided the correct solution. 

A greedy algorithm is a good solution for a scheduling problem but in MSDS 460, we used integer or binary linear programming to solve scheduling problems by minimizing cost to get an optimum solutions. I find linear programming  visually easier to understand.

I have two nested loops in my greedy algorithm function. First is the day loop and second is the employee loop. Based on this, I think the complexity is O(n^2).

The code for the greedy algorithm can be optimized further, but i feel time complexity would be the same O(n^2)

# Discussion and Executive Summary

A greedy algorithm follows the problem-solving heuristic of finding an optimal choice at each step as it attempts to find the overall optimal way to solve the entire problem. The solution above is just one of many possible optimal solutions to this problem. Overall, the greedy algorithm does a pretty good job of finding the optimum solution with the given constraints but if we add additional constraints, the complexity will increase and the algorithm may not find an optimum solution but may find a good enough solution.

Greedy algorithms are one of the heuristic ways of finding a good solution to an NP-complete problem where we can't confirm the optimum solution. A greedy algorithm can find a good enough solution.

# Alternate solution if we change the overtime cut off to 10 and change the number of employees to 5

In [15]:


# create varable to calcuate cost

work_overtime = 20
work_regular = 15

# create weekdays
employees = ['employee_1', 'employee_2', 'employee_3', 'employee_4', 'employee_5']

# min to max work hours per employee from 1 to 12
work_hours = np.linspace(1,15,15)

work_hours


# list of week days

days = ['mon','tue','wed','thur','fri','sat','sun']

In [16]:
employee_schedule(10)

{('employee_1', 'mon'): [10.0],
 ('employee_2', 'mon'): [10.0],
 ('employee_3', 'mon'): [4.0],
 ('employee_4', 'tue'): [10.0],
 ('employee_5', 'tue'): [10.0],
 ('employee_1', 'tue'): [4.0],
 ('employee_2', 'wed'): [10.0],
 ('employee_3', 'wed'): [10.0],
 ('employee_4', 'wed'): [4.0],
 ('employee_5', 'thur'): [10.0],
 ('employee_1', 'thur'): [10.0],
 ('employee_2', 'thur'): [4.0],
 ('employee_3', 'fri'): [10.0],
 ('employee_4', 'fri'): [10.0],
 ('employee_5', 'fri'): [4.0],
 ('employee_1', 'sat'): [10.0],
 ('employee_2', 'sat'): [10.0],
 ('employee_3', 'sat'): [4.0],
 ('employee_4', 'sun'): [10.0],
 ('employee_5', 'sun'): [10.0],
 ('employee_1', 'sun'): [4.0]}